apiVersion: v1
kind: Service
metadata:
  name:      ods-service
  namespace: ods-service
  labels:
    app: ods-service
spec:
  type:     ClusterIP
  selector:
    app: ods-service
  ports:
    - name:       http
      port:       80
      targetPort: 8080
      protocol:   TCP
